# Generated by Django 5.2.6 on 2025-10-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0002_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='categories',
        ),
        migrations.AddField(
            model_name='schedule',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Auto-created based on stock levels'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StockTakeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weighting', models.IntegerField(choices=[(1, 'Low Priority'), (2, 'Medium Priority'), (3, 'High Priority'), (4, 'Critical Priority')], default=2, help_text='Higher weighting = more frequent stock takes needed')),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('auto_schedule_threshold', models.IntegerField(default=5, help_text='Auto-create stock take when items drop below this quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take_groups', to='stock_take.category')),
            ],
            options={
                'ordering': ['-weighting', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='stock_take_groups',
            field=models.ManyToManyField(blank=True, to='stock_take.stocktakegroup'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_take_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='stock_take.stocktakegroup'),
        ),
    ]
