# Generated by Django 5.2.6 on 2025-10-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0003_remove_schedule_categories_schedule_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Date when the schedule was marked as completed', null=True),
        ),
    ]
