# Generated by Django 5.2.6 on 2025-11-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0004_add_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sale_number', models.CharField(max_length=6)),
                ('customer_number', models.CharField(max_length=6)),
                ('order_date', models.DateField()),
                ('fit_date', models.DateField()),
                ('boards_po', models.CharField(max_length=6)),
            ],
        ),
    ]
