# Generated by Django 5.2.6 on 2025-11-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boards_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
