# Generated by Django 5.2.6 on 2025-11-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0007_boardspo_alter_order_boards_po'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardspo',
            options={},
        ),
        migrations.RemoveField(
            model_name='boardspo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='boardspo',
            name='updated_at',
        ),
    ]
