# Generated by Django 5.2.6 on 2025-11-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0008_alter_boardspo_options_remove_boardspo_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='boards_po',
        ),
    ]
