# Generated by Django 5.2.6 on 2025-11-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0009_remove_order_boards_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boards_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stock_take.boardspo'),
        ),
    ]
