# Generated by Django 5.2.6 on 2025-11-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0010_order_boards_po'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNXItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('matname', models.CharField(max_length=100)),
                ('cleng', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cwidth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cnt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.CharField(max_length=200)),
                ('boards_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnx_items', to='stock_take.boardspo')),
            ],
        ),
    ]
