# Generated by Django 5.2.6 on 2025-11-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0011_pnxitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='job_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('remedial', 'Remedial'), ('warranty', 'Warranty')], default='sale', max_length=20),
        ),
    ]
