# Generated by Django 5.2.6 on 2025-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0013_order_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='boards_ordered',
        ),
        migrations.AddField(
            model_name='boardspo',
            name='boards_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
