# Generated by Django 5.2.6 on 2025-11-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0014_remove_order_boards_ordered_boardspo_boards_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_style', models.CharField(max_length=100)),
                ('style_colour', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colour', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('ordered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_doors', to='stock_take.order')),
            ],
        ),
    ]
