# Generated by Django 5.2.6 on 2025-11-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0015_osdoor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billable', models.BooleanField(default=True)),
                ('is_os_door', models.BooleanField(default=False, help_text='True if this is an OS Door accessory (DOR_VNL_OSD_MTM)')),
                ('required', models.BooleanField(default=False, help_text='Required for OS Doors')),
                ('ordered', models.BooleanField(default=False, help_text='Ordered for OS Doors')),
                ('missing', models.BooleanField(default=False, help_text='True if SKU not found in stock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='stock_take.order')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='stock_take.stockitem')),
            ],
        ),
    ]
