# Generated by Django 5.2.6 on 2025-11-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0016_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='os_doors_required',
            field=models.BooleanField(default=False, help_text='True if OS Doors are required for this order'),
        ),
    ]
