# Generated by Django 5.2.6 on 2025-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0017_add_os_doors_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='os_doors_po',
            field=models.CharField(blank=True, help_text='PO number when OS Doors are ordered', max_length=50),
        ),
    ]
