# Generated by Django 5.2.6 on 2025-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0018_add_os_doors_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_items_ordered',
            field=models.BooleanField(default=False, help_text='Manual confirmation that all items have been ordered'),
        ),
    ]
