# Generated by Django 5.2.6 on 2025-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0019_order_all_items_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anthill_id',
            field=models.CharField(blank=True, help_text='Anthill CRM Customer ID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='workguru_id',
            field=models.CharField(blank=True, help_text='WorkGuru Project ID', max_length=20),
        ),
    ]
