# Generated by Django 5.2.6 on 2025-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0021_substitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='billable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
