# Generated by Django 5.2.6 on 2025-11-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0022_alter_substitution_billable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='replacement_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
