# Generated by Django 5.2.6 on 2025-11-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0023_alter_substitution_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_csv',
            field=models.FileField(blank=True, help_text='Original uploaded CSV file', null=True, upload_to='order_csvs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_csv',
            field=models.FileField(blank=True, help_text='Processed CSV with substitutions applied', null=True, upload_to='order_csvs/'),
        ),
    ]
