# Generated by Django 5.2.6 on 2025-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0024_order_original_csv_order_processed_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='csv_has_missing_items',
            field=models.BooleanField(default=False, help_text='True if the uploaded CSV has unresolved missing items that need substitution'),
        ),
    ]
