# Generated by Django 5.2.6 on 2025-11-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0025_order_csv_has_missing_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVSkipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_skip_items', to='stock_take.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('order', 'sku')},
            },
        ),
    ]
