# Generated by Django 5.2.6 on 2025-11-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0026_csvskipitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvskipitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_skip_items', to='stock_take.order'),
        ),
    ]
