# Generated by Django 5.2.6 on 2025-11-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0027_alter_csvskipitem_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='csvskipitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='csvskipitem',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='unique_order_sku_skipitem'),
        ),
        migrations.AddConstraint(
            model_name='csvskipitem',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True)), fields=('sku',), name='unique_global_sku_skipitem'),
        ),
    ]
