# Generated by Django 5.2.6 on 2025-11-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0028_alter_csvskipitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_csv_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the original CSV was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_csv_created_at',
            field=models.DateTimeField(blank=True, help_text='When the processed CSV was created', null=True),
        ),
    ]
