# Generated by Django 5.2.6 on 2025-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0029_order_original_csv_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnxitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
