# Generated by Django 5.2.6 on 2025-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0030_pnxitem_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnxitem',
            options={'ordering': ['barcode', 'matname', 'customer']},
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity that has been received', max_digits=10),
        ),
    ]
