# Generated by Django 5.2.6 on 2025-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0031_alter_pnxitem_options_pnxitem_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdoor',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity that has been received', max_digits=10),
        ),
    ]
