# Generated by Django 6.0 on 2025-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0032_osdoor_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='tacking_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('non-stock', 'Non-Stock'), ('not-classified', 'Not-Classified')], default='not-classified', max_length=30),
        ),
    ]
