# Generated by Django 6.0 on 2025-12-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0033_stockitem_tacking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='tacking_type',
            new_name='tracking_type',
        ),
    ]
