# Generated by Django 6.0 on 2025-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0034_rename_tacking_to_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='sku',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='tracking_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('non-stock', 'Non-Stock'), ('not-classified', 'Not-Classified')], db_index=True, default='not-classified', max_length=30),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tracking_type', 'quantity'], name='stock_take__trackin_23bbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['category', 'tracking_type'], name='stock_take__categor_48ee17_idx'),
        ),
    ]
