# Generated by Django 6.0 on 2026-01-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0035_alter_stockitem_name_alter_stockitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='min_order_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
