# Generated by Django 6.0 on 2026-01-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0036_stockitem_min_order_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedial_number', models.CharField(help_text='Unique remedial reference number', max_length=20, unique=True)),
                ('reason', models.TextField(help_text='Reason for remedial work')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('customer_number', models.CharField(max_length=6)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('scheduled_date', models.DateField(blank=True, help_text='Date remedial work is scheduled', null=True)),
                ('completed_date', models.DateField(blank=True, help_text='Date remedial was completed', null=True)),
                ('os_doors_required', models.BooleanField(default=False)),
                ('os_doors_po', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('all_items_ordered', models.BooleanField(default=False)),
                ('anthill_id', models.CharField(blank=True, max_length=20)),
                ('workguru_id', models.CharField(blank=True, max_length=20)),
                ('boards_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remedials', to='stock_take.boardspo')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedials', to='stock_take.order')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RemedialAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('remedial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='stock_take.remedial')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_take.stockitem')),
            ],
        ),
    ]
