# Generated by Django 6.0 on 2026-01-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0037_remedial_remedialaccessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_date', models.DateField(help_text='Scheduled fit date')),
                ('interior_completed', models.BooleanField(default=False, help_text='Interior fit completed')),
                ('door_completed', models.BooleanField(default=False, help_text='Door fit completed')),
                ('accessories_completed', models.BooleanField(default=False, help_text='Accessories fit completed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the fit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_appointments', to='stock_take.order')),
            ],
            options={
                'ordering': ['fit_date', 'order__last_name'],
            },
        ),
    ]
