# Generated by Django 6.0 on 2026-01-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0038_fitappointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitappointment',
            options={'ordering': ['fit_date', 'fitter', 'order__last_name']},
        ),
        migrations.AddField(
            model_name='fitappointment',
            name='fitter',
            field=models.CharField(choices=[('R', 'Ross'), ('G', 'Gavin'), ('S', 'Stuart'), ('P', 'Paddy')], default='R', help_text='Assigned fitter', max_length=1),
        ),
    ]
