# Generated by Django 6.0 on 2026-01-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0039_alter_fitappointment_options_fitappointment_fitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitappointment',
            name='materials_completed',
            field=models.BooleanField(default=False, help_text='Materials delivered/ready'),
        ),
    ]
