# Generated by Django 6.0 on 2026-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0040_fitappointment_materials_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accessories_completed',
            field=models.BooleanField(default=False, help_text='Accessories fit completed'),
        ),
        migrations.AddField(
            model_name='order',
            name='door_completed',
            field=models.BooleanField(default=False, help_text='Door fit completed'),
        ),
        migrations.AddField(
            model_name='order',
            name='interior_completed',
            field=models.BooleanField(default=False, help_text='Interior fit completed'),
        ),
        migrations.AddField(
            model_name='order',
            name='materials_completed',
            field=models.BooleanField(default=False, help_text='Materials delivered/ready'),
        ),
    ]
