# Generated by Django 6.0 on 2026-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0041_order_accessories_completed_order_door_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paperwork_completed',
            field=models.BooleanField(default=False, help_text='Paperwork completed'),
        ),
    ]
