# Generated by Django 6.0 on 2026-01-14 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0042_order_paperwork_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitappointment',
            name='remedial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fit_appointments', to='stock_take.remedial'),
        ),
        migrations.AlterField(
            model_name='fitappointment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fit_appointments', to='stock_take.order'),
        ),
    ]
