# Generated by Django 6.0 on 2026-01-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0043_fitappointment_remedial_alter_fitappointment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workflow stage', max_length=200)),
                ('phase', models.CharField(choices=[('enquiry', 'Enquiry'), ('lead', 'Lead'), ('sale', 'Sale')], help_text='Which phase this stage belongs to', max_length=20)),
                ('role', models.CharField(choices=[('customer_support', 'Customer Support'), ('design', 'Design'), ('fitter', 'Fitter'), ('operations', 'Operations'), ('manufacturing', 'Manufacturing'), ('enquiry', 'Enquiry')], help_text='Which role is responsible for this stage', max_length=30)),
                ('description', models.TextField(help_text='Description of what needs to be done in this stage')),
                ('expected_days', models.IntegerField(blank=True, help_text='Expected number of days for this stage', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which stages appear')),
            ],
            options={
                'ordering': ['order', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_started_at', models.DateTimeField(auto_now_add=True)),
                ('stage_updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_progress', to='stock_take.order')),
                ('current_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_in_stage', to='stock_take.workflowstage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the task', max_length=300)),
                ('order', models.IntegerField(default=0, help_text='Order in which tasks appear')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='stock_take.workflowstage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, help_text='User who completed the task', max_length=100)),
                ('order_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='stock_take.orderworkflowprogress')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_take.workflowtask')),
            ],
            options={
                'ordering': ['task__order'],
                'unique_together': {('order_progress', 'task')},
            },
        ),
    ]
