# Generated by Django 6.0 on 2026-01-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0044_workflowstage_orderworkflowprogress_workflowtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attachment for this task', null=True, upload_to='workflow_attachments/'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this task completion'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='task_type',
            field=models.CharField(choices=[('record', 'Record Checkbox'), ('requirement', 'Requirement Checkbox'), ('attachment', 'Attachment Field')], default='record', help_text='Type of task', max_length=20),
        ),
    ]
