# Generated by Django 6.0 on 2026-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0045_taskcompletion_attachment_taskcompletion_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='selected_option',
            field=models.CharField(blank=True, help_text='Selected option for radio/dropdown tasks', max_length=200),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for radio/dropdown (e.g., "Brochure,Design Appointment,Both")'),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='role',
            field=models.CharField(choices=[('customer-support', 'Customer Support'), ('design', 'Design'), ('fitter', 'Fitter'), ('operations', 'Operations'), ('manufacturing', 'Manufacturing'), ('enquiry', 'Enquiry')], help_text='Which role is responsible for this stage', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='task_type',
            field=models.CharField(choices=[('record', 'Record Checkbox'), ('requirement', 'Requirement Checkbox'), ('attachment', 'Attachment Field'), ('radio', 'Radio Buttons'), ('dropdown', 'Dropdown Menu')], default='record', help_text='Type of task', max_length=20),
        ),
    ]
