# Generated by Django 6.0 on 2026-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0046_taskcompletion_selected_option_workflowtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdoor',
            name='po_number',
            field=models.CharField(blank=True, help_text='PO Number for tracking OS Doors orders', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='task_type',
            field=models.CharField(choices=[('record', 'Record Checkbox'), ('requirement', 'Requirement Checkbox'), ('attachment', 'Attachment Field'), ('radio', 'Radio Buttons'), ('dropdown', 'Dropdown Menu'), ('decision_matrix', 'Decision Matrix')], default='record', help_text='Type of task', max_length=20),
        ),
    ]
