# Generated by Django 6.0 on 2026-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0047_osdoor_po_number_alter_workflowtask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardspo',
            name='csv_file',
            field=models.FileField(blank=True, help_text='CSV version of the PNX file', null=True, upload_to='boards_po_files/'),
        ),
    ]
