# Generated by Django 6.0 on 2026-01-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0048_boardspo_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('anthill_customer_id', models.CharField(blank=True, help_text='Anthill CRM Customer ID', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='installation_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of installation', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='manufacturing_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of manufacturing', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='materials_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of materials', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_value_exc_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value excluding VAT', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_value_inc_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value including VAT', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stock_take.customer'),
        ),
    ]
