# Generated by Django 6.0 on 2026-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0049_customer_order_installation_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdoor',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per door', max_digits=10),
        ),
    ]
