# Generated by Django 6.0 on 2026-01-28 14:10

from django.db import migrations


def migrate_customers_from_orders(apps, schema_editor):
    """Migrate customer data from Order model to Customer model"""
    Order = apps.get_model('stock_take', 'Order')
    Customer = apps.get_model('stock_take', 'Customer')
    
    # Get all orders
    orders = Order.objects.all()
    
    # Track created customers to avoid duplicates
    customer_map = {}  # Key: (first_name, last_name, postcode), Value: Customer instance
    
    print(f"\nMigrating customers from {orders.count()} orders...")
    
    for order in orders:
        # Skip if order already has a customer linked
        if order.customer_id:
            continue
        
        # Skip if no customer data in order
        if not order.first_name and not order.last_name:
            continue
        
        # Create a unique key for this customer (case-insensitive)
        # Use first_name, last_name, and postcode to identify unique customers
        first_name = (order.first_name or '').strip()
        last_name = (order.last_name or '').strip()
        postcode = (order.postcode or '').strip().upper()
        
        customer_key = (first_name.lower(), last_name.lower(), postcode.lower())
        
        # Check if we've already created this customer
        if customer_key in customer_map:
            customer = customer_map[customer_key]
        else:
            # Try to find existing customer in database
            existing_customer = Customer.objects.filter(
                first_name__iexact=first_name,
                last_name__iexact=last_name,
                postcode__iexact=postcode
            ).first()
            
            if existing_customer:
                customer = existing_customer
            else:
                # Create new customer
                customer = Customer.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    anthill_customer_id=order.anthill_id or '',
                    address=order.address or '',
                    postcode=postcode
                )
                print(f"Created customer: {customer.first_name} {customer.last_name} ({customer.postcode})")
            
            customer_map[customer_key] = customer
        
        # Link order to customer
        order.customer = customer
        order.save(update_fields=['customer'])
    
    print(f"Migration complete. Created/linked {len(customer_map)} unique customers.")


def reverse_migration(apps, schema_editor):
    """Reverse the migration by unlinking customers from orders"""
    Order = apps.get_model('stock_take', 'Order')
    
    # Unlink all customers from orders
    Order.objects.all().update(customer=None)
    print("Reversed customer migration - all orders unlinked from customers.")


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0050_osdoor_cost_price'),
    ]

    operations = [
        migrations.RunPython(migrate_customers_from_orders, reverse_migration),
    ]
