# Generated by Django 6.0 on 2026-01-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0052_designer_order_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for this worker', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for this fitter', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('petrol', 'Petrol'), ('materials', 'Materials'), ('other', 'Other')], default='petrol', max_length=20)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='stock_take.order')),
                ('fitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stock_take.fitter')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_type', models.CharField(choices=[('installation', 'Installation'), ('manufacturing', 'Manufacturing')], max_length=20)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked', max_digits=5)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Rate at time of entry', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of work performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='stock_take.factoryworker')),
                ('fitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='stock_take.fitter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='stock_take.order')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
