# Generated by Django 6.0 on 2026-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0053_factoryworker_fitter_expense_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for installation', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate at time of entry', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked', max_digits=5, null=True),
        ),
    ]
