# Generated by Django 6.0 on 2026-01-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0054_timesheet_price_alter_timesheet_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='helper',
            field=models.ForeignKey(blank=True, help_text='Additional party for installation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_timesheets', to='stock_take.fitter'),
        ),
    ]
