# Generated by Django 6.0 on 2026-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0055_timesheet_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fully_costed',
            field=models.BooleanField(default=False, help_text='Mark as fully costed for reporting'),
        ),
    ]
