# Generated by Django 6.0 on 2026-02-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0056_add_fully_costed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnxitem',
            name='articlename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='grain',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='ordername',
            field=models.CharField(blank=True, default='', help_text='Order/Sale number from PNX', max_length=100),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='partdesc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='prfid1',
            field=models.CharField(blank=True, default='', help_text='Edge profile 1', max_length=100),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='prfid2',
            field=models.CharField(blank=True, default='', help_text='Edge profile 2', max_length=100),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='prfid3',
            field=models.CharField(blank=True, default='', help_text='Edge profile 3', max_length=100),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='prfid4',
            field=models.CharField(blank=True, default='', help_text='Edge profile 4', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowstage',
            name='role',
            field=models.CharField(choices=[('customer-support', 'Customer Support'), ('design', 'Design'), ('fitter', 'Fitter'), ('operations', 'Operations'), ('manufacturing', 'Manufacturing'), ('enquiry', 'Enquiry'), ('waiting', 'Waiting Period')], help_text='Which role is responsible for this stage', max_length=30),
        ),
    ]
