# Generated by Django 5.2.6 on 2026-02-10 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0058_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='par_level',
            field=models.IntegerField(default=0, help_text='Minimum stock level - alerts when stock falls below this'),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Stock quantity at this point in time')),
                ('change_amount', models.IntegerField(help_text='Amount changed (positive for additions, negative for usage)')),
                ('change_type', models.CharField(choices=[('stock_take', 'Stock Take'), ('purchase', 'Purchase Order'), ('sale', 'Sale/Usage'), ('adjustment', 'Manual Adjustment'), ('initial', 'Initial Stock')], default='adjustment', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='PO number, order number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='stock_take.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock_item', '-created_at'], name='stock_take__stock_i_b86f2b_idx')],
            },
        ),
    ]
