# Generated by Django 5.2.6 on 2026-02-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0059_stockitem_par_level_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workguru_id', models.IntegerField(help_text='WorkGuru PO ID', unique=True)),
                ('number', models.CharField(help_text='PO Number (e.g., PO1479)', max_length=50)),
                ('display_number', models.CharField(help_text='Display number with revision', max_length=50)),
                ('revision', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_number', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.CharField(blank=True, max_length=20)),
                ('expected_date', models.CharField(blank=True, max_length=20)),
                ('received_date', models.CharField(blank=True, max_length=20)),
                ('invoice_date', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forecast_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_currency_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
                ('delivery_address_1', models.CharField(blank=True, max_length=255)),
                ('delivery_address_2', models.CharField(blank=True, max_length=255)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('sent_to_supplier', models.CharField(blank=True, max_length=50)),
                ('sent_to_accounting', models.CharField(blank=True, max_length=50)),
                ('billable', models.BooleanField(default=False)),
                ('is_advanced', models.BooleanField(default=False)),
                ('is_rfq', models.BooleanField(default=False)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('received_by_name', models.CharField(blank=True, max_length=200)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Full JSON from WorkGuru API', null=True)),
            ],
            options={
                'ordering': ['-workguru_id'],
                'indexes': [models.Index(fields=['workguru_id'], name='stock_take__workgur_e85612_idx'), models.Index(fields=['number'], name='stock_take__number_632860_idx'), models.Index(fields=['status'], name='stock_take__status_6eb3df_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('order_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('invoice_price', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock_take.purchaseorder')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='stock_take.stockitem')),
            ],
        ),
    ]
