# Generated by Django 5.2.6 on 2026-02-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0060_purchaseorder_purchaseorderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
