# Generated by Django 5.2.6 on 2026-02-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0061_alter_purchaseorder_delivery_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
