# Generated by Django 5.2.6 on 2026-02-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0062_alter_purchaseorder_delivery_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='creator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(blank=True, default='GBP', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='display_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sent_to_accounting',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sent_to_supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, default='Draft', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
