# Generated by Django 5.2.6 on 2026-02-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0065_alter_customer_options_customer_abn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderproduct',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='accounting_system_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amount_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='base_currency_tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cis_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='client_id_wg',
            field=models.IntegerField(blank=True, help_text='WorkGuru Client ID', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='creation_time_wg',
            field=models.CharField(blank=True, help_text='WorkGuru creation timestamp', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_due_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoiced_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_landed_costs_po',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_modification_time_wg',
            field=models.CharField(blank=True, help_text='WorkGuru last modification timestamp', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_used_on_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='expense_account_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='product_id',
            field=models.IntegerField(blank=True, help_text='WorkGuru Product ID', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantity field from API', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='received_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tax_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tax_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='unit_cost',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='workguru_id',
            field=models.IntegerField(blank=True, help_text='WorkGuru product line ID', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='abn',
            field=models.CharField(blank=True, help_text='Tax / ABN / VAT number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_terms_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='estimate_lead_time',
            field=models.IntegerField(blank=True, help_text='Estimated lead time in days', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='number_of_credit_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='price_tier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_tax_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
