# Generated by Django 5.2.6 on 2026-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0067_alter_purchaseorder_expected_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='creation_time_wg',
            field=models.CharField(blank=True, help_text='WorkGuru creation timestamp', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_due_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='last_modification_time_wg',
            field=models.CharField(blank=True, help_text='WorkGuru last modification timestamp', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='received_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
