# Generated by Django 5.2.6 on 2026-02-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0068_alter_purchaseorder_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='box_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Box height in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='box_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Box length in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='box_quantity',
            field=models.IntegerField(blank=True, help_text='Number of items per box', null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='box_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Box width in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='stock_take.supplier'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in mm', max_digits=10, null=True),
        ),
    ]
