# Generated by Django 5.2.6 on 2026-02-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0070_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('accounting', 'Accounting'), ('director', 'Director'), ('user', 'User'), ('franchise', 'Franchise')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stock_take.role'),
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_codename', models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('boards_summary', 'Boards Summary'), ('os_doors_summary', 'OS Doors Summary'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Stock List'), ('stock_take', 'Stock Take'), ('completed_stock_takes', 'Completed Stock Takes'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Generate PNX & CSV'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('tickets', 'Tickets')], max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to='stock_take.role')),
            ],
            options={
                'ordering': ['role', 'page_codename'],
                'unique_together': {('role', 'page_codename')},
            },
        ),
    ]
