# Generated by Django 6.0 on 2026-02-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0071_role_userprofile_role_pagepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('invoices', 'Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('boards_summary', 'Boards Summary'), ('os_doors_summary', 'OS Doors Summary'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Stock List'), ('stock_take', 'Stock Take'), ('completed_stock_takes', 'Completed Stock Takes'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Generate PNX & CSV'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('tickets', 'Tickets')], max_length=50),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workguru_id', models.IntegerField(help_text='WorkGuru Invoice ID', unique=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_id', models.IntegerField(blank=True, help_text='WorkGuru Client ID', null=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('project_number', models.CharField(blank=True, max_length=100)),
                ('project_id', models.IntegerField(blank=True, help_text='WorkGuru Project ID', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sent_to_accounting', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Void', 'Void')], default='Draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=255)),
                ('client_po', models.CharField(blank=True, help_text='Client PO number', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('is_overdue', models.BooleanField(default=False)),
                ('xero_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Full API response', null=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='Last sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to local Customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='stock_take.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Link to local Order record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='stock_take.order')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workguru_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tax_name', models.CharField(blank=True, max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='stock_take.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workguru_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('name', models.CharField(blank=True, help_text='Payment name / note', max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sent_to_accounting', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock_take.invoice')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
