# Generated by Django 5.2.6 on 2026-02-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0073_add_purchase_order_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_allocations', to='stock_take.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stock_take.purchaseorderproduct')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
