# Generated by Django 5.2.6 on 2026-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0075_claim_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdocument',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, help_text='Groups related PDFs together, e.g. 1111_Radley_022115', max_length=255),
        ),
    ]
