# Generated by Django 5.2.6 on 2026-02-13 17:16

import os
from django.db import migrations


def backfill_group_key(apps, schema_editor):
    ClaimDocument = apps.get_model('stock_take', 'ClaimDocument')
    for doc in ClaimDocument.objects.filter(group_key=''):
        if doc.file:
            filename = os.path.basename(doc.file.name)
            name = os.path.splitext(filename)[0]
            parts = name.rsplit('_', 1)
            if len(parts) > 1:
                doc.group_key = parts[0]
                # Also backfill customer_name if empty
                if not doc.customer_name:
                    name_parts = name.split('_')
                    if len(name_parts) >= 3:
                        doc.customer_name = name_parts[1]
                doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0076_claimdocument_group_key'),
    ]

    operations = [
        migrations.RunPython(backfill_group_key, migrations.RunPython.noop),
    ]
