# Generated by Django 5.2.6 on 2026-02-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0081_add_claim_download_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='read_by_admin',
            field=models.BooleanField(default=False, help_text='Has an admin read this ticket?'),
        ),
    ]
