# Generated by Django 5.2.6 on 2026-02-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0082_add_ticket_read_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lead / contact name', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('phone', 'Phone'), ('email', 'Email'), ('walk_in', 'Walk-In'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated value', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_to_customer', models.ForeignKey(blank=True, help_text='Customer created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='stock_take.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
