# Generated by Django 5.2.6 on 2026-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0083_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether PO email has been sent to supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the PO email was sent', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='email_sent_to',
            field=models.CharField(blank=True, help_text='Email address PO was sent to', max_length=255, null=True),
        ),
    ]
