# Generated by Django 5.2.6 on 2026-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0084_purchaseorder_email_sent_purchaseorder_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='anthill_created_date',
            field=models.DateTimeField(blank=True, help_text='When this customer was created in Anthill CRM', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, help_text='Anthill location / branch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='anthill_created_date',
            field=models.DateTimeField(blank=True, help_text='When this lead was created in Anthill CRM', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='anthill_customer_id',
            field=models.CharField(blank=True, help_text='Anthill CRM Customer ID', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, help_text='Anthill location / branch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
