# Generated by Django 5.2.6 on 2026-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0085_add_anthill_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_location',
            field=models.CharField(blank=True, default='', help_text='Currently selected site location', max_length=100),
        ),
    ]
