# Generated by Django 5.2.6 on 2026-02-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0087_suppliercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='supplier_code',
            field=models.CharField(blank=True, default='', help_text="Supplier's own product/part code", max_length=100),
        ),
    ]
