# Generated by Django 5.2.6 on 2026-02-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0089_add_title_to_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthillSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthill_activity_id', models.CharField(help_text='Anthill activity ID', max_length=30, unique=True)),
                ('anthill_customer_id', models.CharField(blank=True, db_index=True, help_text='Anthill customer ID this sale belongs to', max_length=20)),
                ('activity_type', models.CharField(blank=True, help_text='Activity type e.g. "Sale"', max_length=100)),
                ('status', models.CharField(blank=True, help_text='Activity status e.g. "Complete"', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name from Anthill', max_length=255)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_date', models.DateTimeField(blank=True, help_text='When this activity was created in Anthill', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked local customer record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anthill_sales', to='stock_take.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Linked local order if one exists', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anthill_sale', to='stock_take.order')),
            ],
            options={
                'verbose_name': 'Anthill Sale',
                'verbose_name_plural': 'Anthill Sales',
                'ordering': ['-activity_date'],
            },
        ),
    ]
