# Generated by Django 5.2.6 on 2026-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0090_add_anthill_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_boards_pos',
            field=models.ManyToManyField(blank=True, help_text='Additional boards POs for this order', related_name='additional_orders', to='stock_take.boardspo'),
        ),
    ]
