# Generated by Django 5.2.6 on 2026-02-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0092_invoice_workguru_id_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='cut_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cut-to-size height in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='cut_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cut-to-size width in mm', max_digits=10, null=True),
        ),
    ]
