# Generated by Django 5.2.6 on 2026-02-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0094_widen_varchar50_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('phone', 'Phone'), ('email', 'Email'), ('walk_in', 'Walk-In'), ('advertisement', 'Advertisement'), ('anthill', 'Anthill CRM'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('stock', 'Stock'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('label', models.CharField(blank=True, help_text='Display label, e.g. "Stock" or customer name', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Linked local order (null for stock entries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_projects', to='stock_take.order')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='stock_take.purchaseorder')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
