# Generated by Django 5.2.6 on 2026-02-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0095_add_purchaseorderproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='po_invoices/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, help_text='Invoice date', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='stock_take.purchaseorder')),
            ],
            options={
                'ordering': ['-date', '-uploaded_at'],
            },
        ),
    ]
