# Generated by Django 5.2.6 on 2026-02-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0096_add_purchaseorderinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='supplier_sku',
            field=models.CharField(blank=True, default='', help_text="Supplier's SKU for this product", max_length=100),
        ),
    ]
