# Generated by Django 5.2.6 on 2026-02-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0097_add_supplier_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('invoices', 'Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('boards_summary', 'Boards Summary'), ('os_doors_summary', 'OS Doors Summary'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Stock List'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Generate PNX & CSV'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
    ]
