# Generated by Django 5.2.6 on 2026-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0098_remove_completed_stock_takes_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, help_text='Purchase orders this invoice is attached to', related_name='linked_invoices', to='stock_take.purchaseorder'),
        ),
    ]
