# Generated by Django 5.2.6 on 2026-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0099_add_invoice_purchase_orders_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF or document attached to this invoice', null=True, upload_to='invoice_attachments/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='linked_products',
            field=models.ManyToManyField(blank=True, help_text='Specific PO line items this invoice covers', related_name='linked_invoices', to='stock_take.purchaseorderproduct'),
        ),
    ]
