# Generated by Django 5.2.6 on 2026-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0100_add_invoice_attachment_and_linked_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer', models.CharField(help_text='Designer / salesperson name', max_length=100)),
                ('customer_name', models.CharField(help_text='Customer full name', max_length=200)),
                ('postcode', models.CharField(blank=True, help_text='Customer postcode', max_length=20)),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('appointment_time', models.TimeField(help_text='Time of the appointment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
