# Generated by Django 5.2.6 on 2026-02-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0101_salesappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesappointment',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the appointment', null=True),
        ),
        migrations.AddField(
            model_name='salesappointment',
            name='event_type',
            field=models.CharField(choices=[('appointment', 'Sales Appointment'), ('showroom_cover', 'Showroom Cover'), ('unavailable', 'Unavailable')], default='appointment', help_text='Type of event', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesappointment',
            name='appointment_time',
            field=models.TimeField(help_text='Start time of the appointment'),
        ),
        migrations.AlterField(
            model_name='salesappointment',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer full name', max_length=200),
        ),
        migrations.AlterField(
            model_name='salesappointment',
            name='designer',
            field=models.CharField(blank=True, help_text='Designer / salesperson name', max_length=100),
        ),
    ]
