# Generated by Django 5.2.6 on 2026-02-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0102_salesappointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='price',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Associated PO for installation cost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='stock_take.purchaseorder'),
        ),
    ]
