# Generated by Django 6.0 on 2026-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0103_remove_timesheet_helper_remove_timesheet_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='GBP', help_text='ISO currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight / shipping cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_vat_inclusive',
            field=models.BooleanField(default=True, help_text='Whether the total entered includes VAT'),
        ),
    ]
