# Generated by Django 6.0 on 2026-02-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0104_invoice_freight_currency_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='VAT percentage rate', max_digits=5),
        ),
    ]
