# Generated by Django 6.0 on 2026-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0105_invoice_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
