# Generated by Django 5.2.6 on 2026-03-02 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0106_alter_order_fit_date_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('invoices', 'Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('boards_summary', 'Boards Summary'), ('os_doors_summary', 'OS Doors Summary'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Stock List'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Order Generator'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(db_index=True, help_text='Name/identifier of the sync script', max_length=100)),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this run started')),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='success', max_length=10)),
                ('records_created', models.IntegerField(default=0, help_text='Number of records created this run')),
                ('records_updated', models.IntegerField(default=0, help_text='Number of records updated this run')),
                ('errors', models.IntegerField(default=0, help_text='Number of errors encountered')),
                ('notes', models.TextField(blank=True, help_text='Free-text summary or error details')),
            ],
            options={
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['script_name', '-ran_at'], name='stock_take__script__d9be33_idx')],
            },
        ),
    ]
