# Generated by Django 5.2.6 on 2026-03-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0107_add_synclog_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factoryworker',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='factoryworker',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order workers are displayed (lower = first)'),
        ),
    ]
