# Generated by Django 5.2.6 on 2026-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0110_add_purchase_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthillsale',
            name='assigned_to_id',
            field=models.CharField(blank=True, help_text='Anthill user ID of the assigned person', max_length=20),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Name of the assigned person e.g. "Karen.Wild"', max_length=150),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='balance_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='contract_number',
            field=models.CharField(blank=True, help_text='Anthill contract number e.g. "NTG-KW-420968"', max_length=100),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='deposit_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='door_type',
            field=models.CharField(blank=True, help_text='e.g. "Sliding", "Hinged"', max_length=100),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='fit_from_date',
            field=models.CharField(blank=True, help_text='Fit From Date from Anthill (text field)', max_length=50),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='goods_due_in',
            field=models.CharField(blank=True, help_text='Goods Due In date from Anthill (text field)', max_length=50),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='products_included',
            field=models.CharField(blank=True, help_text='e.g. "Sliding"', max_length=255),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='range_name',
            field=models.CharField(blank=True, help_text='Product range e.g. "Core"', max_length=100),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='sale_type_id',
            field=models.CharField(blank=True, help_text='Anthill sale type ID (1=Room, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='sale_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Value Inc VAT', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='anthillsale',
            name='source',
            field=models.CharField(blank=True, help_text='Lead source e.g. "Website", "Repeat Customer"', max_length=100),
        ),
        migrations.AlterField(
            model_name='anthillsale',
            name='activity_type',
            field=models.CharField(blank=True, help_text='Activity type e.g. "Room Sale"', max_length=100),
        ),
        migrations.AlterField(
            model_name='anthillsale',
            name='status',
            field=models.CharField(blank=True, help_text='Sale status: open / won / dead', max_length=50),
        ),
    ]
