# Generated by Django 6.0 on 2026-03-03 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0112_timesheet_purchase_invoice_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('job_finished', 'Job Marked as Finished'), ('job_unfinished', 'Job Marked as Unfinished'), ('order_created', 'Order Created'), ('order_deleted', 'Order Deleted'), ('po_created', 'Purchase Order Created'), ('po_deleted', 'Purchase Order Deleted'), ('invoice_created', 'Purchase Invoice Created'), ('invoice_deleted', 'Purchase Invoice Deleted'), ('timesheet_added', 'Timesheet Added'), ('timesheet_deleted', 'Timesheet Deleted'), ('other', 'Other')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='stock_take.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
