# Generated by Django 5.2.6 on 2026-03-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0113_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, help_text='Purchase orders this supplier invoice is associated with', related_name='linked_purchase_invoices', to='stock_take.purchaseorder'),
        ),
    ]
