# Generated by Django 5.2.6 on 2026-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0114_purchase_invoice_po_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT rate percentage (e.g. 20.00 for 20%)', max_digits=5, null=True),
        ),
    ]
