# Generated by Django 5.2.6 on 2026-03-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0115_supplier_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_os_doors_pos',
            field=models.ManyToManyField(blank=True, help_text='Additional OS Doors POs for this order', related_name='additional_os_doors_orders', to='stock_take.purchaseorder'),
        ),
    ]
