# Generated by Django 6.0 on 2026-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0119_anthillsale_paid_in_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthillsale',
            name='fit_date',
            field=models.DateField(blank=True, help_text='Confirmed installation/fit date (from Anthill appointments or copied from linked Order)', null=True),
        ),
        migrations.AlterField(
            model_name='anthillpayment',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Date of the payment', null=True),
        ),
        migrations.AlterField(
            model_name='anthillpayment',
            name='location',
            field=models.CharField(blank=True, help_text='Location (not available from Xero)', max_length=100),
        ),
        migrations.AlterField(
            model_name='anthillpayment',
            name='payment_type',
            field=models.CharField(blank=True, help_text='e.g. "Deposit", "Balance Payment" — derived from Xero payment reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='anthillpayment',
            name='status',
            field=models.CharField(blank=True, help_text='"Confirmed", "Authorised", etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='anthillpayment',
            name='user_name',
            field=models.CharField(blank=True, help_text='User who recorded the payment (not available from Xero)', max_length=150),
        ),
        migrations.AlterField(
            model_name='anthillsale',
            name='fit_from_date',
            field=models.CharField(blank=True, help_text='Fit From Date from Anthill custom field (text)', max_length=50),
        ),
    ]
