# Generated by Django 6.0 on 2026-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0120_add_fit_date_to_anthillsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accessories_not_required',
            field=models.BooleanField(default=False, help_text='Accessories are not required for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='boards_not_required',
            field=models.BooleanField(default=False, help_text='Boards are not required for this order'),
        ),
    ]
