# Generated by Django 5.2.6 on 2026-03-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0122_accessory_allocated_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('job_finished', 'Job Marked as Finished'), ('job_unfinished', 'Job Marked as Unfinished'), ('order_created', 'Order Created'), ('order_deleted', 'Order Deleted'), ('po_created', 'Purchase Order Created'), ('po_deleted', 'Purchase Order Deleted'), ('invoice_created', 'Purchase Invoice Created'), ('invoice_deleted', 'Purchase Invoice Deleted'), ('timesheet_added', 'Timesheet Added'), ('timesheet_deleted', 'Timesheet Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('stock_adjusted', 'Stock Adjusted'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='RaumplusDraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Draft Order', help_text='Descriptive name for this draft', max_length=200)),
                ('items', models.JSONField(default=list, help_text='Serialised list of order row dicts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raumplus_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
