# Generated by Django 5.2.6 on 2026-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0123_alter_activitylog_event_type_raumplusdraftorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthillOrderToPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('date_sold', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('total_value', models.CharField(blank=True, max_length=50)),
                ('workflow_status', models.CharField(blank=True, max_length=100)),
                ('fit_date', models.CharField(blank=True, max_length=50)),
                ('order_url', models.URLField(blank=True, max_length=1000)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anthill Order to Place',
                'verbose_name_plural': 'Anthill Orders to Place',
                'ordering': ['date_sold'],
            },
        ),
    ]
