# Generated by Django 5.2.6 on 2026-03-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0124_anthill_order_to_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('page_action', 'Page Action'), ('job_finished', 'Job Marked as Finished'), ('job_unfinished', 'Job Marked as Unfinished'), ('order_created', 'Order Created'), ('order_deleted', 'Order Deleted'), ('po_created', 'Purchase Order Created'), ('po_deleted', 'Purchase Order Deleted'), ('invoice_created', 'Purchase Invoice Created'), ('invoice_deleted', 'Purchase Invoice Deleted'), ('timesheet_added', 'Timesheet Added'), ('timesheet_deleted', 'Timesheet Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('stock_adjusted', 'Stock Adjusted'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
