# Generated by Django 6.0 on 2026-03-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0125_add_page_action_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('page_action', 'Page Action'), ('job_finished', 'Job Marked as Finished'), ('job_unfinished', 'Job Marked as Unfinished'), ('order_created', 'Order Created'), ('order_deleted', 'Order Deleted'), ('po_created', 'Purchase Order Created'), ('po_deleted', 'Purchase Order Deleted'), ('invoice_created', 'Purchase Invoice Created'), ('invoice_deleted', 'Purchase Invoice Deleted'), ('timesheet_added', 'Timesheet Added'), ('timesheet_deleted', 'Timesheet Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('stock_adjusted', 'Stock Adjusted'), ('error', 'Error'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('invoices', 'Invoices'), ('purchase_invoices', 'Purchase Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('boards_summary', 'Boards Summary'), ('os_doors_summary', 'OS Doors Summary'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Products'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Order Generator'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
    ]
