# Generated by Django 6.0 on 2026-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0126_add_error_event_type_to_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthillsale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sliderobes Credit / discount that reduces the effective sale value', max_digits=12),
        ),
    ]
