# Generated by Django 5.2.6 on 2026-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0127_add_discount_to_anthillsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthillpayment',
            name='ignored',
            field=models.BooleanField(default=False, help_text='If True, this payment is excluded from financial calculations.'),
        ),
    ]
