# Generated by Django 5.2.6 on 2026-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0128_add_payment_ignored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthillpayment',
            name='anthill_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment ID from the source system (Xero PaymentID, etc.)', max_length=100),
        ),
    ]
