# Generated by Django 6.0 on 2026-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0130_add_resolved_to_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitappointment',
            name='fit_duration',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of days for the fit (1 = single day)'),
        ),
    ]
