# Generated by Django 5.2.6 on 2026-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0131_add_fit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardspo',
            name='dwg_file',
            field=models.FileField(blank=True, help_text='DWG drawing file for manufacturer', null=True, upload_to='boards_po_files/'),
        ),
    ]
