# Generated by Django 6.0 on 2026-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0132_add_dwg_file_to_boardspo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_purchase_order_id',
            field=models.CharField(blank=True, help_text='Xero PurchaseOrder ID (GUID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_pushed_at',
            field=models.DateTimeField(blank=True, help_text='When PO was pushed to Xero', null=True),
        ),
    ]
