# Generated by Django 6.0 on 2026-03-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0133_add_xero_purchase_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='fitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='stock_take.fitter'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_type',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('fitter', 'Fitter')], default='supplier', max_length=10),
        ),
    ]
