# Generated by Django 5.2.6 on 2026-03-31 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0135_add_fitter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Associated PO for this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stock_take.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stock_take.order'),
        ),
    ]
