# Generated by Django 6.0 on 2026-04-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0136_add_purchase_order_to_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='stock_take.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='parent_po',
            field=models.ForeignKey(blank=True, help_text='The PO this was split from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_children', to='stock_take.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('page_action', 'Page Action'), ('job_finished', 'Job Marked as Finished'), ('job_unfinished', 'Job Marked as Unfinished'), ('order_created', 'Order Created'), ('order_deleted', 'Order Deleted'), ('po_created', 'Purchase Order Created'), ('po_deleted', 'Purchase Order Deleted'), ('invoice_created', 'Purchase Invoice Created'), ('invoice_deleted', 'Purchase Invoice Deleted'), ('timesheet_added', 'Timesheet Added'), ('timesheet_deleted', 'Timesheet Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('stock_adjusted', 'Stock Adjusted'), ('po_split', 'Purchase Order Split'), ('po_status_change', 'PO Status Change'), ('po_updated', 'Purchase Order Updated'), ('error', 'Error'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
