# Generated by Django 6.0 on 2026-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0137_activitylog_purchase_order_purchaseorder_parent_po_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Freight / shipping cost', max_digits=10),
        ),
    ]
