# Generated by Django 5.2.6 on 2026-04-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0138_add_freight_cost_to_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='anthill_payments_data',
            field=models.JSONField(blank=True, help_text='Cached Anthill payment scrape results', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_payment_search',
            field=models.DateTimeField(blank=True, help_text='When payment data was last searched', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='xero_invoices_data',
            field=models.JSONField(blank=True, help_text='Cached Xero invoice search results', null=True),
        ),
    ]
