# Generated by Django 6.0 on 2026-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0140_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='gallery/thumbs/'),
        ),
    ]
