# Generated by Django 6.0 on 2026-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0141_gallery_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dashboard_layout',
            field=models.JSONField(blank=True, help_text='Per-user dashboard widget layout config', null=True),
        ),
    ]
