# Generated by Django 5.2.6 on 2026-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0142_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardspo',
            name='is_angled',
            field=models.BooleanField(default=False, help_text='Whether this PO contains angled/tapered boards'),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='left_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left edge height for angled boards (mm)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pnxitem',
            name='right_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right edge height for angled boards (mm)', max_digits=10, null=True),
        ),
    ]
