# Generated by Django 5.2.6 on 2026-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0143_add_angled_boards_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnxitem',
            name='top_edge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Top edge flat width for 5-piece doors (mm), 0 if no top edge', max_digits=10),
        ),
    ]
