# Generated by Django 6.0 on 2026-04-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0144_add_top_edge_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStageDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(help_text='Date this stage was completed')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_dates', to='stock_take.order')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dates', to='stock_take.workflowstage')),
            ],
            options={
                'ordering': ['stage__order'],
                'unique_together': {('order', 'stage')},
            },
        ),
    ]
