# Generated by Django 6.0 on 2026-04-14 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0145_add_workflow_stage_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='average_landed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average cost per item across POs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product_url',
            field=models.URLField(blank=True, default='', help_text='Link to supplier product page', max_length=500),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_source', models.CharField(choices=[('invoice', 'Invoice Price Update'), ('manual', 'Manual Edit'), ('import', 'CSV Import')], default='manual', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='PO number or other reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stock_take.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
