# Generated by Django 6.0 on 2026-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0146_stockitem_average_landed_price_stockitem_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='anthill_payment_status',
            field=models.CharField(blank=True, help_text='Confirmed / Unconfirmed from Anthill', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, help_text='Anthill contract number e.g. BFS-SD-423514', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(blank=True, help_text='Anthill user who created the payment', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Cash, Credit Card, Debit Card, BACS, Finance, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received_date',
            field=models.DateField(blank=True, help_text='Date payment was received per Anthill', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, help_text='Deposit, Final Balance, Part Payment, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='showroom',
            field=models.CharField(blank=True, help_text='Anthill showroom / location', max_length=100),
        ),
    ]
