# Generated by Django 6.0 on 2026-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0147_invoice_anthill_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitappointment',
            name='fitter',
            field=models.CharField(choices=[('R', 'Ross Middleton'), ('G', 'Gavin Reynolds'), ('S', 'Stuart Stevenson'), ('P', 'Paddy'), ('M', 'Mo Hassan'), ('J', 'Jamie McPhail'), ('T', 'Gary Tumelty'), ('E', 'External Delivery'), ('X', 'Ripout Team')], default='R', help_text='Assigned fitter', max_length=1),
        ),
    ]
