# Generated by Django 6.0 on 2026-04-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0148_update_fitter_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ratio', models.DecimalField(decimal_places=2, default=1, help_text='How many of linked_product per 1 of product', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='stock_take.stockitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='stock_take.stockitem')),
            ],
            options={
                'ordering': ['linked_product__name'],
                'unique_together': {('product', 'linked_product')},
            },
        ),
    ]
