# Generated by Django 6.0 on 2026-04-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0149_add_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitterUploadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('sale_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_user_agent', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitter_upload_submissions', to='stock_take.customer')),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitter_upload_submissions', to='stock_take.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fitter_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FitterUploadPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/staging/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/staging/thumbs/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_sources', to='stock_take.galleryimage')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stock_take.fitteruploadsubmission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
