# Generated by Django 6.0 on 2026-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0160_raumplusoption_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, help_text='Form name or page URL', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Full raw payload from WordPress', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Enquiry',
                'verbose_name_plural': 'Website Enquiries',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('website_enquiries', 'Website Enquiries'), ('invoices', 'Invoices'), ('purchase_invoices', 'Purchase Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Products'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Order Generator'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('gallery', 'Gallery'), ('about', 'About'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
    ]
