# Generated by Django 5.2.6 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0161_add_website_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteenquiry',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websiteenquiry',
            name='contact_for_design_appointment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteenquiry',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='websiteenquiry',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='websiteenquiry',
            name='newsletter_signup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteenquiry',
            name='region',
            field=models.CharField(blank=True, help_text='Region selection such as UK or ROI', max_length=30),
        ),
    ]
