from django.db import migrations, models


def seed_raumplus_rules(apps, schema_editor):
    RaumplusOrderingRule = apps.get_model('stock_take', 'RaumplusOrderingRule')

    defaults = [
        {
            'name': 'rule_style_buffer',
            'label': 'Apply style buffer',
            'value_type': 'int',
            'default_value': '8',
            'enabled_name': 'rule_apply_style_buffer',
            'enabled_default': True,
            'unit_suffix': 'units',
            'default_help_text': 'Styles add extra units to avoid running out immediately after shortages are covered. Value is extra units to add for style items (S150/S750/S751/S753).',
            'sort_order': 10,
        },
        {
            'name': 'rule_min_line_cost',
            'label': 'Enforce minimum line cost',
            'value_type': 'decimal',
            'default_value': '100.00',
            'enabled_name': 'rule_enforce_min_line_cost',
            'enabled_default': True,
            'unit_prefix': '£',
            'default_help_text': 'When on, quantities are increased so each line reaches at least this minimum pre-VAT line cost.',
            'sort_order': 20,
        },
        {
            'name': 'rule_min_order_value',
            'label': 'Minimum order value (inc VAT)',
            'value_type': 'decimal',
            'default_value': '5000.00',
            'enabled_name': 'rule_enable_min_order_value',
            'enabled_default': True,
            'unit_prefix': '£',
            'default_help_text': 'Target total order value including VAT; suggestions are added until this value is reached.',
            'sort_order': 30,
        },
        {
            'name': 'rule_vat_percent',
            'label': 'VAT percent',
            'value_type': 'decimal',
            'default_value': '19.0',
            'enabled_name': 'rule_enable_vat_percent',
            'enabled_default': True,
            'unit_suffix': '%',
            'default_help_text': 'VAT rate used to convert ex-VAT totals to inc-VAT totals for threshold checks.',
            'sort_order': 40,
        },
        {
            'name': 'rule_apply_weighted_average',
            'label': 'Use weighted average model',
            'value_type': 'bool',
            'default_value': '1',
            'enabled_default': True,
            'default_help_text': 'Prediction blends recent usage with long-term baseline instead of using recent trend only.',
            'sort_order': 50,
        },
        {
            'name': 'rule_recent_weight_percent',
            'label': 'Recent weight percent',
            'value_type': 'decimal',
            'default_value': '70.0',
            'enabled_name': 'rule_apply_weighted_average',
            'enabled_default': True,
            'unit_suffix': '%',
            'default_help_text': 'Percent of forecast driven by recent usage; the remainder is long-term baseline weight.',
            'sort_order': 60,
        },
        {
            'name': 'rule_prediction_buffer_percent',
            'label': 'Prediction buffer percent',
            'value_type': 'decimal',
            'default_value': '20.0',
            'enabled_name': 'rule_apply_weighted_average',
            'enabled_default': True,
            'unit_suffix': '%',
            'default_help_text': 'Safety buffer added on top of forecast demand to reduce stockout risk.',
            'sort_order': 70,
        },
        {
            'name': 'rule_apply_gasket_target',
            'label': 'Apply gasket 4mm target',
            'value_type': 'bool',
            'default_value': '1',
            'enabled_default': True,
            'default_help_text': 'When on, gasket 4mm uses an absolute stock floor, not just demand forecast.',
            'sort_order': 80,
        },
        {
            'name': 'rule_gasket_target_stock',
            'label': 'Gasket 4mm target stock',
            'value_type': 'int',
            'default_value': '800',
            'enabled_name': 'rule_apply_gasket_target',
            'enabled_default': True,
            'unit_suffix': 'units',
            'default_help_text': 'Minimum stock level to maintain for gasket 4mm when gasket target rule is enabled.',
            'sort_order': 90,
        },
        {
            'name': 'rule_apply_track_rules',
            'label': 'Apply rail/track divisors',
            'value_type': 'bool',
            'default_value': '1',
            'enabled_default': True,
            'default_help_text': 'When on, rail and track quantities are normalized by divisor rules rather than raw accessory counts.',
            'sort_order': 100,
        },
        {
            'name': 'rule_bottom_track_divisor',
            'label': 'Bottom rail/track divisor',
            'value_type': 'int',
            'default_value': '4',
            'enabled_name': 'rule_apply_track_rules',
            'enabled_default': True,
            'unit_suffix': 'doors',
            'default_help_text': 'Divisor for bottom rails and double bottom tracks. Example: 4 means ceil(total doors / 4).',
            'sort_order': 110,
        },
        {
            'name': 'rule_top_track_divisor',
            'label': 'Single/triple track divisor',
            'value_type': 'int',
            'default_value': '8',
            'enabled_name': 'rule_apply_track_rules',
            'enabled_default': True,
            'unit_suffix': 'doors',
            'default_help_text': 'Divisor for single and triple tracks. Example: 8 means ceil(total doors / 8).',
            'sort_order': 120,
        },
        {
            'name': 'rule_apply_dividing_rail_pack',
            'label': 'Apply dividing rail extra pack',
            'value_type': 'bool',
            'default_value': '1',
            'enabled_default': True,
            'default_help_text': 'When on, an extra pack is added if projected dividing rail stock remains under threshold.',
            'sort_order': 130,
        },
        {
            'name': 'rule_dividing_rail_threshold',
            'label': 'Dividing rail threshold',
            'value_type': 'int',
            'default_value': '8',
            'enabled_name': 'rule_apply_dividing_rail_pack',
            'enabled_default': True,
            'unit_suffix': 'units',
            'default_help_text': 'Stock floor for dividing rails. If projected stock stays below this value, one extra pack is added.',
            'sort_order': 140,
        },
        {
            'name': 'rule_apply_priority_weighting',
            'label': 'Apply priority weighting',
            'value_type': 'bool',
            'default_value': '1',
            'enabled_default': True,
            'default_help_text': 'When on, priority multipliers influence which non-shortage items are suggested first.',
            'sort_order': 150,
        },
        {
            'name': 'rule_top_roller_priority',
            'label': 'Top roller priority',
            'value_type': 'decimal',
            'default_value': '3.0',
            'enabled_name': 'rule_apply_priority_weighting',
            'enabled_default': True,
            'unit_suffix': 'x',
            'default_help_text': 'Multiplier for top rollers in suggestion ranking. Higher values push these items earlier.',
            'sort_order': 160,
        },
        {
            'name': 'rule_bottom_roller_priority',
            'label': 'Bottom roller priority',
            'value_type': 'decimal',
            'default_value': '2.5',
            'enabled_name': 'rule_apply_priority_weighting',
            'enabled_default': True,
            'unit_suffix': 'x',
            'default_help_text': 'Multiplier for bottom rollers in suggestion ranking.',
            'sort_order': 170,
        },
        {
            'name': 'rule_frame_screw_priority',
            'label': 'Frame screw priority',
            'value_type': 'decimal',
            'default_value': '2.5',
            'enabled_name': 'rule_apply_priority_weighting',
            'enabled_default': True,
            'unit_suffix': 'x',
            'default_help_text': 'Multiplier for frame screws in suggestion ranking.',
            'sort_order': 180,
        },
        {
            'name': 'rule_gasket_4mm_priority',
            'label': 'Gasket 4mm priority',
            'value_type': 'decimal',
            'default_value': '2.0',
            'enabled_name': 'rule_apply_priority_weighting',
            'enabled_default': True,
            'unit_suffix': 'x',
            'default_help_text': 'Multiplier for gasket 4mm in suggestion ranking.',
            'sort_order': 190,
        },
        {
            'name': 'rule_gasket_6mm_priority',
            'label': 'Gasket 6mm priority',
            'value_type': 'decimal',
            'default_value': '0.5',
            'enabled_name': 'rule_apply_priority_weighting',
            'enabled_default': True,
            'unit_suffix': 'x',
            'default_help_text': 'Multiplier for gasket 6mm in suggestion ranking.',
            'sort_order': 200,
        },
        {
            'name': 'rule_gasket_8mm_priority',
            'label': 'Gasket 8mm priority',
            'value_type': 'decimal',
            'default_value': '0.5',
            'enabled_name': 'rule_apply_priority_weighting',
            'enabled_default': True,
            'unit_suffix': 'x',
            'default_help_text': 'Multiplier for gasket 8mm in suggestion ranking.',
            'sort_order': 210,
        },
        {
            'name': 'rule_apply_exclusions',
            'label': 'Apply excluded-items filter',
            'value_type': 'bool',
            'default_value': '1',
            'enabled_default': True,
            'default_help_text': 'When on, excluded keywords are filtered out from suggestion candidates.',
            'sort_order': 220,
        },
    ]

    for item in defaults:
        defaults_kwargs = {
            'label': item['label'],
            'value_type': item['value_type'],
            'default_value': item.get('default_value', ''),
            'enabled_name': item.get('enabled_name', ''),
            'enabled_default': item.get('enabled_default', True),
            'unit_prefix': item.get('unit_prefix', ''),
            'unit_suffix': item.get('unit_suffix', ''),
            'default_help_text': item.get('default_help_text', '-'),
            'help_text': item.get('default_help_text', '-'),
            'sort_order': item.get('sort_order', 0),
            'is_active': True,
        }
        RaumplusOrderingRule.objects.update_or_create(
            name=item['name'],
            defaults=defaults_kwargs,
        )

    # If legacy overrides exist, migrate those help texts to the new model.
    try:
        RaumplusRuleTextOverride = apps.get_model('stock_take', 'RaumplusRuleTextOverride')
        for override in RaumplusRuleTextOverride.objects.all():
            RaumplusOrderingRule.objects.filter(name=override.rule_name).update(help_text=override.help_text)
    except LookupError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0166_raumplusruletextoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaumplusOrderingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('decimal', 'Decimal'), ('bool', 'Boolean')], max_length=20)),
                ('default_value', models.CharField(blank=True, default='', max_length=50)),
                ('enabled_name', models.CharField(blank=True, default='', max_length=100)),
                ('enabled_default', models.BooleanField(default=True)),
                ('unit_prefix', models.CharField(blank=True, default='', max_length=10)),
                ('unit_suffix', models.CharField(blank=True, default='', max_length=20)),
                ('default_help_text', models.TextField(blank=True, default='-')),
                ('help_text', models.TextField(blank=True, default='-')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raumplus Ordering Rule',
                'verbose_name_plural': 'Raumplus Ordering Rules',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(seed_raumplus_rules, migrations.RunPython.noop),
    ]
