# Generated by Django 6.0 on 2026-05-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0174_pair_balance_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, choices=[('iphone', 'iPhone'), ('samsung', 'Samsung'), ('google', 'Google'), ('other', 'Other')], default='', max_length=20)),
                ('model', models.CharField(blank=True, default='', help_text='e.g. SE (2nd Generation), A53 5G', max_length=100)),
                ('chip', models.CharField(blank=True, default='', help_text='e.g. A13 Bionic, Snapdragon 670', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', help_text='IMEI / Serial number', max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('ok', 'Ok'), ('poor', 'Poor')], default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sim_removed', 'SIM Removed'), ('locked', 'Locked'), ('cracked_screen', 'Cracked Screen'), ('marketing', 'Marketing Phone'), ('spare', 'Spare'), ('other', 'Other')], default='active', max_length=20)),
                ('purchase_date', models.CharField(blank=True, default='', help_text='e.g. November 2021', max_length=50)),
                ('security_updates_until', models.CharField(blank=True, default='', help_text='e.g. 2027', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('sim_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly SIM cost', max_digits=8, null=True)),
                ('is_esim', models.BooleanField(default=False, help_text='Tick if this is an eSIM-only entry')),
                ('is_dead', models.BooleanField(default=False, help_text='Device no longer in use')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
                'ordering': ['is_dead', 'last_name', 'first_name'],
            },
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('website_enquiries', 'Website Enquiries'), ('invoices', 'Invoices'), ('purchase_invoices', 'Purchase Invoices'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Products'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Order Generator'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('mobile_devices', 'Mobile Devices'), ('laptop_devices', 'Laptops'), ('desktop_devices', 'Desktops'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('gallery', 'Gallery'), ('about', 'About'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
    ]
