# Generated by Django 6.0 on 2026-05-06 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0175_it_mobile_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiledevice',
            options={'ordering': ['is_dead', 'assigned_user__last_name', 'assigned_user__first_name'], 'verbose_name': 'Mobile Device', 'verbose_name_plural': 'Mobile Devices'},
        ),
        migrations.RemoveField(
            model_name='mobiledevice',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mobiledevice',
            name='last_name',
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Atlas user this device is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
