# Generated by Django 6.0 on 2026-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0176_mobile_device_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. iPhone 15 Pro, Samsung S23+', max_length=100)),
                ('device_type', models.CharField(choices=[('iphone', 'iPhone'), ('samsung', 'Samsung'), ('google', 'Google'), ('other', 'Other')], default='iphone', max_length=20)),
                ('model', models.CharField(blank=True, default='', help_text='e.g. 15 Pro, S23+', max_length=100)),
                ('chip', models.CharField(blank=True, default='', help_text='e.g. A17 Pro', max_length=100)),
                ('security_updates_until', models.CharField(blank=True, default='', help_text='e.g. 2027', max_length=50)),
            ],
            options={
                'verbose_name': 'Phone Template',
                'verbose_name_plural': 'Phone Templates',
                'ordering': ['device_type', 'name'],
            },
        ),
    ]
