# Generated by Django 6.0 on 2026-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0177_phone_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='xero_id',
            field=models.CharField(blank=True, help_text='Xero InvoiceID once pushed to Xero', max_length=100),
        ),
    ]
