# Generated by Django 6.0 on 2026-05-07 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0178_add_xero_id_to_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('website_enquiries', 'Website Enquiries'), ('invoices', 'Invoices'), ('purchase_invoices', 'Purchase Invoices'), ('accounts_payable', 'Accounts Payable'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Products'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('generate_materials', 'Order Generator'), ('database_check', 'Database Check'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('mobile_devices', 'Mobile Devices'), ('laptop_devices', 'Laptops'), ('desktop_devices', 'Desktops'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('gallery', 'Gallery'), ('about', 'About'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
        migrations.CreateModel(
            name='MailboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_message_id', models.CharField(help_text='Microsoft Graph API message ID', max_length=1000, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.CharField(blank=True, max_length=254)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body_preview', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='True once a Purchase Invoice has been created from this email')),
                ('attachment_names', models.TextField(blank=True, help_text='JSON array of {id, name, content_type, size} for non-inline attachments')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_emails', to='stock_take.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'Mailbox Email',
                'verbose_name_plural': 'Mailbox Emails',
                'ordering': ['-received_at'],
            },
        ),
    ]
