# Generated by Django 6.0 on 2026-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0179_mailboxemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxemail',
            name='is_ignored',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the email has been marked as ignored/not relevant'),
        ),
    ]
