# Generated by Django 6.0 on 2026-05-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0180_mailboxemail_ignored'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Emails from this address are skipped during sync', max_length=254, unique=True)),
                ('note', models.CharField(blank=True, help_text='Optional note explaining why this address is exempted', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mailbox Exemption',
                'verbose_name_plural': 'Mailbox Exemptions',
                'ordering': ['email_address'],
            },
        ),
    ]
