# Generated by Django 6.0 on 2026-05-07 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0181_mailboxexemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxemail',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who created the purchase invoice from this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
