# Generated by Django 6.0 on 2026-05-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0182_add_processed_by_to_mailboxemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='reference',
            field=models.CharField(blank=True, help_text="Supplier's own reference / filename", max_length=255),
        ),
    ]
