# Generated by Django 6.0 on 2026-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0183_add_reference_to_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_reference',
            field=models.CharField(blank=True, help_text="Supplier's own invoice number or reference code", max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='reference',
            field=models.CharField(blank=True, help_text='Internal reference / filename (without extension)', max_length=255),
        ),
    ]
