# Generated by Django 6.0 on 2026-05-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0185_supplier_xero_default_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverheadPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated OPO reference e.g. OPO-0001', max_length=20, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('rent_rates', 'Rent & Rates'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('marketing', 'Marketing & Advertising'), ('it_software', 'IT & Software'), ('office', 'Office & Sundries'), ('professional', 'Professional Services'), ('vehicles', 'Vehicles & Transport'), ('other', 'Other Overhead')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('date', models.DateField(blank=True, help_text='PO / order date', null=True)),
                ('expected_date', models.DateField(blank=True, help_text='Expected invoice or payment date', null=True)),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_invoices', models.ManyToManyField(blank=True, help_text='Accounts-payable invoices associated with this overhead PO', related_name='overhead_pos', to='stock_take.purchaseinvoice')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overhead_pos', to='stock_take.supplier')),
            ],
            options={
                'verbose_name': 'Overhead Purchase Order',
                'verbose_name_plural': 'Overhead Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
