# Generated by Django 6.0 on 2026-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0188_usersiterole_ordervalidationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoicelineitem',
            name='line_date',
            field=models.DateField(blank=True, help_text='Date of work or service', null=True),
        ),
    ]
