# Generated by Django 6.0 on 2026-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0190_purchaseinvoicelineitem_is_fit_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per square metre for cut-to-size items (e.g. glass). When set, order cost is auto-calculated from cut dimensions.', max_digits=10, null=True),
        ),
    ]
