# Generated by Django 6.0 on 2026-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0191_add_price_per_sqm_to_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxEmailFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pattern', models.CharField(help_text='Full email address or @domain.com to match against the sender', max_length=254, unique=True)),
                ('tab', models.CharField(choices=[('rjl', 'RJL'), ('group', 'Group')], help_text='Which tab matching emails are routed to', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mailbox Email Filter',
                'verbose_name_plural': 'Mailbox Email Filters',
                'ordering': ['tab', 'email_pattern'],
            },
        ),
        migrations.AddField(
            model_name='mailboxemail',
            name='tab',
            field=models.CharField(blank=True, choices=[('', 'All'), ('rjl', 'RJL'), ('group', 'Group')], db_index=True, default='', help_text='Company entity tab this email is routed to', max_length=20),
        ),
    ]
