# Generated by Django 6.0 on 2026-05-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0193_remedial_action_required_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_sku', models.CharField(help_text='The kit/bundle SKU that replaces all members', max_length=100, unique=True)),
                ('replacement_name', models.CharField(blank=True, help_text='Display name for the kit item', max_length=255)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='mailboxemail',
            name='tab',
            field=models.CharField(blank=True, choices=[('', 'All'), ('rjl', 'RJL'), ('group', 'Group'), ('statements', 'Statements')], db_index=True, default='', help_text='Company entity tab this email is routed to', max_length=20),
        ),
        migrations.CreateModel(
            name='SkuGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='stock_take.skugroup')),
            ],
            options={
                'ordering': ['sku'],
                'unique_together': {('group', 'sku')},
            },
        ),
    ]
