# Generated by Django 6.0 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0195_ordervalidationrequest_component_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(default='GBP', help_text='ISO currency code', max_length=3),
        ),
    ]
