# Generated by Django 6.0 on 2026-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0196_add_currency_to_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT rate applied to this invoice (e.g. 20.00 for 20%)', max_digits=5, null=True),
        ),
    ]
