# Generated by Django 6.0 on 2026-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0197_purchaseinvoice_add_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='specifications',
            field=models.TextField(blank=True, default='', help_text='Technical specifications, one per line — displayed as bullet points'),
        ),
    ]
