# Generated by Django 6.0 on 2026-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0202_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anthillsale',
            name='stock_take__anthsale_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='anthillsale',
            name='stock_take__anthsale_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='stock_take__customer_location_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='glass_not_required',
            field=models.BooleanField(default=True, help_text='Glass does not need to be validated for this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='raumplus_required',
            field=models.BooleanField(default=False, help_text='Raumplus items need to be validated for this order'),
        ),
        migrations.AddField(
            model_name='ordervalidationrequest',
            name='raumplus_checked',
            field=models.BooleanField(default=False, help_text='Validator confirmed Raumplus items are correct'),
        ),
    ]
