# Generated by Django 6.0 on 2026-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0207_add_order_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierEmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pattern', models.CharField(help_text='Full email address (user@domain.com) or domain suffix (@domain.com) to match against the sender', max_length=254, unique=True)),
                ('supplier_name', models.CharField(help_text='Supplier name to pre-fill when a sender matches this rule', max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Supplier Email Rule',
                'verbose_name_plural': 'Supplier Email Rules',
                'ordering': ['email_pattern'],
            },
        ),
    ]
