# Generated by Django 6.0 on 2026-05-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0208_supplier_email_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxemail',
            name='matched_po',
            field=models.ForeignKey(blank=True, help_text='Specific PO matched from PDF scan of the email attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_emails', to='stock_take.purchaseorder'),
        ),
    ]
