# Generated by Django 6.0 on 2026-06-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0212_remedial_action_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxemail',
            name='is_split',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this email has been split into per-attachment child emails (hidden from the inbox)'),
        ),
        migrations.AddField(
            model_name='mailboxemail',
            name='parent_email',
            field=models.ForeignKey(blank=True, help_text='If this email was created by splitting another email, the original it came from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_children', to='stock_take.mailboxemail'),
        ),
    ]
