# Generated by Django 6.0 on 2026-06-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0213_mailboxemail_is_split_mailboxemail_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxemail',
            name='extracted_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount extracted from the PDF attachment during auto-scan', max_digits=12, null=True),
        ),
    ]
