# Generated by Django 6.0 on 2026-06-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0214_mailboxemail_extracted_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desktop Machine',
                'verbose_name_plural': 'Desktop Machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesktopComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock_take.desktopmachine')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
