# Generated by Django 6.0 on 2026-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0218_deactivate_legacy_raumplus_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('website_enquiries', 'Website Enquiries'), ('invoices', 'Invoices'), ('purchase_invoices', 'Purchase Invoices'), ('accounts_payable', 'Accounts Payable'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Products'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('mobile_devices', 'Mobile Devices'), ('laptop_devices', 'Laptops'), ('desktop_devices', 'Desktops'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('gallery', 'Gallery'), ('about', 'About'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
    ]
