# Generated by Django 6.0 on 2026-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0221_calendarblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthillpayment',
            name='full_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original (un-split) payment amount from the source. When the parent invoice is linked to N sales, amount = full_amount / N.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='anthillpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount (GBP). When an invoice is linked to several sales this holds the per-sale split share, not the full value.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='calendarblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='page_codename',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('orders', 'Orders'), ('order_details', 'Order Details'), ('customers', 'Customers'), ('customer_details', 'Customer Details'), ('remedials', 'Remedials'), ('website_enquiries', 'Website Enquiries'), ('invoices', 'Invoices'), ('purchase_invoices', 'Purchase Invoices'), ('accounts_payable', 'Accounts Payable'), ('payments', 'Payments'), ('purchase_orders', 'Purchase Orders'), ('purchase_order_details', 'Purchase Order Details'), ('suppliers', 'Suppliers'), ('supplier_details', 'Supplier Details'), ('material_shortage', 'Stock Shortage Report'), ('raumplus_storage', 'Raumplus Shortage'), ('products', 'Products'), ('product_details', 'Product Details'), ('stock_list', 'Products'), ('stock_take', 'Stock Take'), ('categories', 'Categories'), ('substitutions', 'Substitutions'), ('fit_board', 'Fit Board'), ('timesheets', 'Timesheets'), ('workflow', 'Workflow'), ('map', 'Map'), ('material_report', 'Material Report'), ('costing_report', 'Costing Report'), ('remedial_report', 'Remedial Report'), ('mobile_devices', 'Mobile Devices'), ('laptop_devices', 'Laptops'), ('desktop_devices', 'Desktops'), ('tickets', 'Tickets'), ('claim_service', 'Claim Service'), ('gallery', 'Gallery'), ('about', 'About'), ('admin_panel', 'Admin Panel')], max_length=50),
        ),
    ]
