# Generated by Django 6.0 on 2026-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0222_anthillpayment_full_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_pre_vat',
            field=models.BooleanField(default=True, help_text='If True, the discount is deducted from the net before VAT is calculated; if False, it is deducted from the gross total'),
        ),
    ]
