# Generated by Django 6.0 on 2026-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0223_purchaseinvoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoicelineitem',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
