# Generated by Django 6.0 on 2026-06-29 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0226_alter_activitylog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('office', 'In Office'), ('wfh', 'Working From Home'), ('off', 'Day Off'), ('sick', 'Sick Leave'), ('holiday', 'Holiday'), ('training', 'Training')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The employee this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='stock_take.fitter')),
            ],
            options={
                'ordering': ['date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
