# Generated by Django 6.0 on 2026-06-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0227_employee_calendar_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitter',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Branch / office location (e.g. Belfast, Dublin)', max_length=100),
        ),
    ]
