# Generated by Django 6.0 on 2026-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0228_fitter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number', max_length=100),
        ),
    ]
