# Generated by Django 6.0 on 2026-06-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0230_alter_employeecalendarentry_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCalendarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('status', models.CharField(choices=[('office', 'In Office'), ('wfh', 'Working From Home'), ('off', 'Day Off'), ('sick', 'Sick Leave'), ('holiday', 'Holiday'), ('training', 'Training')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The user this recurring rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee', 'weekday'],
                'unique_together': {('employee', 'weekday')},
            },
        ),
    ]
