# Generated by Django 6.0 on 2026-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0231_employeecalendarrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_department',
            field=models.CharField(choices=[('showroom', 'Showroom'), ('workshop', 'Workshop')], default='showroom', help_text='Which employee-calendar sub-tab this user appears under', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calendar_order',
            field=models.IntegerField(default=0, help_text='Sort position in the employee calendar list'),
        ),
    ]
