# Generated by Django 6.0 on 2026-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0232_userprofile_calendar_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='calendar_department',
        ),
        migrations.AlterField(
            model_name='employeecalendarentry',
            name='status',
            field=models.CharField(choices=[('office', 'In Office'), ('showroom', 'Showroom'), ('workshop', 'Workshop'), ('wfh', 'Working From Home'), ('off', 'Day Off'), ('sick', 'Sick Leave'), ('holiday', 'Holiday'), ('training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeecalendarrule',
            name='status',
            field=models.CharField(choices=[('office', 'In Office'), ('showroom', 'Showroom'), ('workshop', 'Workshop'), ('wfh', 'Working From Home'), ('off', 'Day Off'), ('sick', 'Sick Leave'), ('holiday', 'Holiday'), ('training', 'Training')], max_length=20),
        ),
    ]
