# Generated by Django 6.0 on 2026-06-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0233_remove_userprofile_calendar_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fitter',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked login account for this fitter (used for the Schedule page)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('accounting', 'Accounting'), ('director', 'Director'), ('user', 'User'), ('franchise', 'Franchise'), ('fitter', 'Fitter')], max_length=20, unique=True),
        ),
    ]
