# Generated by Django 6.0 on 2026-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0234_fitter_user_alter_role_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anthillsale',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_number', ''), _negated=True), fields=('contract_number',), name='unique_non_blank_contract_number'),
        ),
    ]
