# Generated by Django 6.0 on 2026-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0236_merge_waiting_into_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='cad_sku',
            field=models.CharField(blank=True, db_index=True, default='', help_text='CAD component code (CODCOMP) that matches this product when generating accessories from CAD data', max_length=100),
        ),
    ]
