# Generated by Django 6.0 on 2026-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0237_stockitem_cad_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='Client name', max_length=255),
        ),
    ]
