# Generated by Django 6.0 on 2026-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0238_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardspo',
            name='pnx_files_hash',
            field=models.CharField(blank=True, db_default='', default='', help_text='Hash of the PNX item set the last time files were generated. Used to detect when the board list has drifted from the files attached to the PO (drives the "Update Files & PO" button).', max_length=64),
        ),
    ]
