# Generated by Django 6.0 on 2026-07-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0242_fitappointment_fit_duration_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitappointment',
            name='starts_pm',
            field=models.BooleanField(default=False, help_text='Job starts in the afternoon (second half of the fit_date) rather than the morning. Shifts the calendar bar right by one half-day.'),
        ),
    ]
