# Generated by Django 6.0 on 2026-07-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0244_alter_pagepermission_page_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name, e.g. "MacBook Pro 14 M4 Pro"', max_length=150)),
                ('cpu', models.CharField(blank=True, default='', max_length=200)),
                ('ram', models.CharField(blank=True, default='', help_text='e.g. "32GB"', max_length=100)),
                ('storage', models.CharField(blank=True, default='', help_text='e.g. "1TB SSD"', max_length=100)),
                ('gpu', models.CharField(blank=True, default='', max_length=200)),
                ('display', models.CharField(blank=True, default='', help_text='e.g. "14\\" 3024×1964"', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Quoted unit price', max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, default='', help_text='Store / supplier', max_length=120)),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laptop Spec',
                'verbose_name_plural': 'Laptop Specs',
                'ordering': ['name'],
            },
        ),
    ]
