# Generated by Django 6.0 on 2026-07-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0245_laptopspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='selected_location',
            field=models.CharField(blank=True, default='', help_text='Selected site location filter — comma-separated list of one or more locations; blank means all locations', max_length=255),
        ),
    ]
