# Generated by Django 6.0 on 2026-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0246_alter_userprofile_selected_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('account', 'On Account'), ('card', 'Card / Website'), ('direct_debit', 'Direct Debit'), ('bank_transfer', 'Bank Transfer'), ('proforma', 'Proforma / Prepaid'), ('other', 'Other')], default='', help_text='How we pay this supplier — e.g. on a credit account, or by card via their website. Blank = unknown.', max_length=20),
        ),
    ]
