# Generated by Django 6.0 on 2026-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_take', '0248_remove_install_date_attempt_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_payment_confirmed',
            field=models.BooleanField(default=False, help_text='Manual confirmation that the stock payment has been taken, for payments not recorded against the sale in Atlas'),
        ),
    ]
